# Generated by Django 4.2 on 2023-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='netstatus',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
